// components/switch.vue
<script setup lang="ts">
type Props = {
  modelValue: boolean;
};

const props = defineProps<Props>()
const emits = defineEmits(['update:modelValue'])

const toggle = () => {
  emits('update:modelValue', !props.modelValue)
}
</script>

<template>
  <div

    h-6
    w-12
    cursor-pointer
    rounded-full
    p-1
    transition-all
    :class="modelValue ? 'bg-teal-500' : 'dark:bg-gray-700 bg-gray-300'"
    @click="toggle"
  >
    <div

      h-4
      w-4
      rounded-full
      bg-gray-100
      shadow
      transition="all ease-out"
      transform="~"
      :class="modelValue ? 'translate-x-6' : 'translate-x-0'"
    />
  </div>
</template>

// frontend/src/components/Switch.tsx
import React, { useState } from 'react';

interface Props {
  onToggle: () => void;
}

const Switch = (props: Props) => {
  const [active, setActive] = useState(false);

  return (
    <div
      className={`w-12 h-18 p-1 flex items-center ${
        active ? 'bg-teal-400' : 'bg-gray-300'
      } rounded-full`}
      onClick={() => {
        props.onToggle();
        setActive(!active);
      }}
    >
      <div
        className={`transform ${
          active ? 'translate-x-5' : ''
        } bg-white shadow-md w-5 h-5 rounded-full duration-150 ease-in-out`}
      ></div>
    </div>
  );
};

export default Switch;
