// src/components/StudentList.tsx
import React from 'react';
import { useSearch } from '~/hooks/useSearch';
import Student from './Student';
import { VERSION } from '~/constants/version';

const StudentList = () => {
  const { keywords, chips, result, count, isLoading, loadMore, resetCache } = useSearch();

  if (isLoading) {
    return <div className="text-xs text-center italic text-gray-500">Loading...</div>;
  } else if (keywords.length < 3 && chips.length === 0) {
    return (
      <div className="text-xs text-center italic text-gray-500">
        Hasil pencarian akan keluar di sini. {VERSION}
        <br />
        Data kurang lengkap?{' '}
        <span className="underline cursor-pointer" onClick={() => resetCache()}>
          Reset cache
        </span>
        .
      </div>
    );
  } else {
    return (
      <>
        <div className="text-xs text-center italic text-gray-500">
          {count === 0
            ? 'Tidak ditemukan apa-apa. Mungkin salah geprek.'
            : `Menunjukan ${count} dari ${result.length} hasil.`}
        </div>
        <div className="pb-4">
          {result.slice(0, count).map((s) => {
            return (
              <div key={s[1]}>
                <Student name={s[0]} facultyId={s[1]} majorId={s[2]} />
                <hr />
              </div>
            );
          })}
        </div>
        <div className="flex justify-center w-full py-2">
          {result.length !== count ? (
            <button
              className=" w-full lg:w-64 rounded text-gray-500 dark:text-gray-100 px-4 py-2 outline-none bg-gray-100 dark:bg-gray-800 hover:bg-gray-100 dark:hover:bg-gray-700 transition duration-150"
              onClick={loadMore}
            >
              Load more...
            </button>
          ) : null}
        </div>
      </>
    );
  }
};

export default StudentList;

// components/home/student-list.vue
<script setup lang="ts">
// const store = useSearch();

// const SPECIALS = ['13518035', '13516030', '18217006', '18219075', '13519101', '13520029'];

// get result on mount
// onMounted(() => {
//   if (store.query.length >= 2) {
//     store.getResult();
//   }
// });

// reset cache/localstorage
// const { t } = useI18n();
</script>

<template>
  <div flex="~ col" justify-center v-if="store.result.length !== 0">
    <TransitionGroup name="list" tag="ul">
      <template v-for="s in store.result.slice(0, store.limit)" :key="s[0].majorID || s[0].tpbID">
        <StudentItem :student="s[0]" :isSpecial="SPECIALS.includes(s[0].majorID!)" />
      </template>
    </TransitionGroup>
    <div flex="~" justify-center mt-2 mx-auto w-full v-if="store.limit < store.result.length">
      <a bg="teal-400 dark:gray-700/70" p="x-4 y-2" cursor="pointer" select-none text-white text-center text-sm rounded
        @click="store.increaseLimit(5)">Geprek lagi!</a>
    </div>
  </div>
</template>
