// src/components/Student.tsx
import React, { useRef } from 'react';
import majorMap from '@/json/list_jurusan.json';
import facultyMap from '@/json/list_fakultas.json';

interface Props {
  name: string;
  facultyId: string;
  majorId: string;
}

const copyToClipboard = (text: string) => {
  navigator.clipboard.writeText(text);
};

const Student = (props: Props) => {
  const nameRef = useRef<HTMLDivElement | null>(null);
  const majorIdRef = useRef<HTMLDivElement | null>(null);
  const facultyIdRef = useRef<HTMLDivElement | null>(null);

  const getMajor = () => {
    if (props.majorId) {
      const majorCode: keyof typeof majorMap = props.majorId.slice(0, 3) as keyof typeof majorMap;
      return majorMap[majorCode];
    }
    return undefined;
  };

  const getFaculty = () => {
    const facultyCode: keyof typeof facultyMap = props.facultyId.slice(
      0,
      3,
    ) as keyof typeof facultyMap;
    return facultyMap[facultyCode];
  };

  const major = getMajor();
  const faculty = getFaculty();

  return (
    <div className="flex justify-between items-center py-2">
      <div>
        <div
          className="text-sm md:text-base font-medium dark:text-gray-200 cursor-pointer hover:animate-pulse"
          ref={nameRef}
          onClick={() => {
            copyToClipboard(nameRef.current?.innerHTML!);
          }}
        >
          {props.name}
        </div>
        <div className="text-xs md:text-sm italic text-gray-500 dark:text-gray-300 select-none">
          {major || faculty}
        </div>
      </div>
      <div>
        {major ? (
          <div
            className={`text-xs md:text-sm text-gray-500  dark:text-gray-300 cursor-pointer hover:animate-pulse`}
            ref={majorIdRef}
            onClick={() => {
              copyToClipboard(majorIdRef.current?.innerHTML!);
            }}
          >
            {props.majorId}
          </div>
        ) : null}
        <div
          className={`text-xs md:text-sm text-gray-500  dark:text-gray-300 ${
            major ? 'select-none' : ''
          } cursor-pointer hover:animate-pulse`}
          ref={facultyIdRef}
          onClick={() => {
            copyToClipboard(facultyIdRef.current?.innerHTML!);
          }}
        >
          {props.facultyId}
        </div>
      </div>
    </div>
  );
};

export default Student;

// src/components/page/home/student.vue
<script setup lang="ts">
import type { Student } from '~/models/Student';
import m from '~/json/majors.json';
import c from '~/json/codes.json';
import { useSettings } from '~/store/settings';
import { MajorMode } from '~/models/MajorMode';

// props
type Props = {
  student: Student;
};

const props = defineProps<Props>();

// remap dicts
const majors = m as { [k: string]: string };
const codes: { [k: string]: string } = {};
for (const [k, v] of Object.entries(c)) {
  codes[v] = k;
}

const { majorMode: mode, showYear } = useSettings();

const getMajorName = () => {
  const prefix = props.student.majorID?.slice(0, 3) ?? props.student.tpbID.slice(0, 3);
  const year = 2000 + parseInt(props.student.tpbID.slice(3, 5));
  const major = majors[prefix];
  const shortened = codes[prefix];

  let result: string;
  switch (mode) {
    case MajorMode.LONG:
      result = `${major}${showYear ? ` ${year}` : ''}`;
      break;
    case MajorMode.SHORT:
      result = `${shortened}${showYear ? `${year}` : ''}`;
      break;
    case MajorMode.BOTH:
      result = `${major} (${shortened}${showYear ? `${year}` : ''})`;
      break;
    default:
      result = `${major}${showYear ? ` ${year}` : ''}`;
      break;
  }

  return result;
};
</script>

<template>
  <div flex justify-between items-center space-x-2 py-2>
    <div>
      <div
        text="sm md:base dark:gray-200"
        font-medium
        cursor-pointer
        hover:animate-pulse
        title="Click to copy!"
      >
        {{ student.name }}
      </div>
      <div text="xs md:sm dark:gray-300" italic select-none>
        {{ getMajorName() }}
      </div>
    </div>
    <div>
      <div
        v-if="student.majorID"
        text="xs md:sm gray-500 dark:gray-300"
        select-none
        cursor-pointer
        hover:animate-pulse
        title="Click to copy!"
      >
        {{ student.majorID }}
      </div>
      <div
        text="xs md:sm gray-500 dark:gray-300"
        select-none
        cursor-pointer
        hover:animate-pulse
        title="Click to copy!"
      >
        {{ student.tpbID }}
      </div>
    </div>
  </div>
</template>
